<?php
add_action( 'acf/include_fields', function() {
	if ( function_exists( 'acf_add_local_field_group' ) ) {

		acf_add_local_field_group( array(
			'key' => 'group_banner000000001',
			'title' => 'Block: Banner',
			'fields' => array(
				array(
					'key' => 'field_banner000000001',
					'label' => 'Immagine desktop',
					'name' => 'immagine_desktop',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'allow_in_bindings' => 0,
					'mime_types' => '',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_banner000000002',
					'label' => 'Immagine mobile',
					'name' => 'immagine_mobile',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'allow_in_bindings' => 0,
					'mime_types' => '',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_banner000000003',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'allow_in_bindings' => 0,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/banner',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'display_title' => '',
			'allow_ai_access' => false,
			'ai_description' => '',
			'acfml_field_group_mode' => 'advanced',
		) );

		acf_add_local_field_group( array(
			'key' => 'group_ssnail_contact',
			'title' => 'Contatti',
			'fields' => array(
				array(
					'key' => 'field_ssnail_contact_heading',
					'name' => 'ssnail_contact_heading',
					'label' => 'Titolo',
					'type' => 'text',
					'default_value' => 'Contattaci',
				),
				array(
					'key' => 'field_ssnail_contact_form_intro',
					'name' => 'ssnail_contact_form_intro',
					'label' => 'Introduzione modulo',
					'type' => 'textarea',
					'rows' => 3,
					'default_value' => 'Compila il modulo per fissare un appuntamento o ricevere maggiori informazioni sui nostri servizi legali.',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/contact',
					),
				),
			),
		) );

		acf_add_local_field_group( array(
			'key' => 'group_ctabtn001',
			'title' => 'Block: CTA Button',
			'fields' => array(
				array(
					'key' => 'field_ctabtn_link',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				array(
					'key' => 'field_ctabtn_variante',
					'label' => 'Variante',
					'name' => 'variante',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'btn-primary' => 'Primary',
						'btn-secondary' => 'Secondary',
						'btn-tertiary' => 'Tertiary',
						'btn-foreground' => 'Foreground',
						'btn-ghost' => 'Ghost',
					),
					'default_value' => 'btn-primary',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
				),
				array(
					'key' => 'field_ctabtn_grande',
					'label' => 'Grande',
					'name' => 'grande',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => 'Aggiunge btn-big (più padding, testo più grande).',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_ctabtn_bordi',
					'label' => 'Bordi netti',
					'name' => 'bordi_netti',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => 'Aggiunge btn-sharp (angoli quadrati).',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/cta-button',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'display_title' => '',
			'allow_ai_access' => false,
			'ai_description' => '',
			'acfml_field_group_mode' => 'advanced',
		) );

		acf_add_local_field_group( array(
			'key' => 'group_68667ee7e93de',
			'title' => 'Block: Image with text',
			'fields' => array(
				array(
					'key' => 'field_68667ee7ed92b',
					'label' => 'Layout',
					'name' => 'layout',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'immagine-destra' => 'Immagine a destra',
						'immagine-sinistra' => 'Immagine a sinistra',
					),
					'default_value' => 'immagine-destra',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_68667ee7ed96a',
					'label' => 'Immagine',
					'name' => 'immagine',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_68667ee7ed9e2',
					'label' => 'Titolo',
					'name' => 'titolo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_68667f0131676',
					'label' => 'Descrizione',
					'name' => 'descrizione',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'wpml_cf_preferences' => 2,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/image-with-text',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'display_title' => '',
			'allow_ai_access' => false,
			'ai_description' => '',
			'acfml_field_group_mode' => 'translation',
		) );

		acf_add_local_field_group( array(
			'key' => 'group_684af3824b262',
			'title' => 'Block: Insight Card',
			'fields' => array(
				array(
					'key' => 'field_684af392fe5f8',
					'label' => 'Stile',
					'name' => 'stile',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'chiaro' => 'Chiaro',
						'scuro' => 'Scuro',
					),
					'default_value' => 'scuro',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_684c2157facbb',
					'label' => 'Layout',
					'name' => 'layout',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'verticale-immagine-testo' => 'Verticale - immagine + testo',
						'quadrato-solo-testo' => 'Quadrato - solo testo',
						'quadrato-titolo-immagine' => 'Quadrato - titolo + immagine',
						'orizzontale' => 'Orizzontale - immagine + testo',
					),
					'default_value' => 'verticale-immagine-testo',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_684af3ccfe5f9',
					'label' => 'Titolo',
					'name' => 'titolo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_684af3d4fe5fa',
					'label' => 'Sottotitolo',
					'name' => 'sottotitolo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_684af3dbfe5fb',
					'label' => 'Descrizione',
					'name' => 'descrizione',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_684c2157facbb',
								'operator' => '!=',
								'value' => 'quadrato-titolo-immagine',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_684af3e2fe5fc',
					'label' => 'Immagine',
					'name' => 'immagine',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_684c2157facbb',
								'operator' => '!=',
								'value' => 'quadrato-solo-testo',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_684af3f4fe5fd',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'allow_in_bindings' => 0,
					'wpml_cf_preferences' => 1,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/insight-card',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'display_title' => '',
			'allow_ai_access' => false,
			'ai_description' => '',
			'acfml_field_group_mode' => 'translation',
		) );

		acf_add_local_field_group( array(
			'key' => 'group_6862b6a640268',
			'title' => 'Block: Posts grid',
			'fields' => array(
				array(
					'key' => 'field_6862b6c35b159',
					'label' => 'Categoria',
					'name' => 'categoria',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'category',
					'add_term' => 0,
					'save_terms' => 0,
					'load_terms' => 0,
					'return_format' => 'id',
					'field_type' => 'checkbox',
					'allow_in_bindings' => 0,
					'bidirectional' => 0,
					'multiple' => 0,
					'allow_null' => 0,
					'bidirectional_target' => array(),
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_6862b7125b15a',
					'label' => 'Numero post',
					'name' => 'numero_post',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 8,
					'min' => 1,
					'max' => 32,
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_6862b6a64567f',
					'label' => 'Stile',
					'name' => 'stile',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'chiaro' => 'Chiaro',
						'scuro' => 'Scuro',
					),
					'default_value' => 'scuro',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_6862b8306577d',
					'label' => 'Layout',
					'name' => 'layout',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'container' => 'Container',
						'full-width' => 'Larghezza piena',
					),
					'default_value' => 'container',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_68638aea28241',
					'label' => 'Bottone Vedi tutti',
					'name' => 'bottone_vedi_tutti',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Visualizzare il bottone "Vedi tutti"?',
					'default_value' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'wpml_cf_preferences' => 1,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/posts-grid',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'display_title' => '',
			'allow_ai_access' => false,
			'ai_description' => '',
			'acfml_field_group_mode' => 'translation',
		) );

		acf_add_local_field_group( array(
			'key' => 'group_684ace5f201c3',
			'title' => 'Block: Slider',
			'fields' => array(
				array(
					'key' => 'field_686bd58d7154a',
					'label' => 'Sorgente schede',
					'name' => 'sorgente_schede',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'elenco-post' => 'Elenco di post',
						'input-schede' => 'Inserimento manuale',
					),
					'default_value' => 'input-schede',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_685145252aa41',
					'label' => 'Altezza slide (in pixel)',
					'name' => 'altezza_slide',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 400,
					'min' => '',
					'max' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_685145412aa42',
					'label' => 'Riempimento immagine',
					'name' => 'riempimento_immagine',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'cover' => 'Ricopri lo spazio',
						'contain' => 'Contieni l\'immagine',
					),
					'default_value' => 'cover',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_686bd5da7154b',
					'label' => 'Elenco post',
					'name' => 'elenco_post',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_686bd58d7154a',
								'operator' => '==',
								'value' => 'elenco-post',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'post_status' => array(
						0 => 'publish',
					),
					'taxonomy' => '',
					'return_format' => 'object',
					'multiple' => 1,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(),
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_684ace5f23db2',
					'label' => 'Schede',
					'name' => 'schede',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_686bd58d7154a',
								'operator' => '==',
								'value' => 'input-schede',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => 'field_684ace5f2671f',
					'button_label' => 'Aggiungi Riga',
					'rows_per_page' => 20,
					'wpml_cf_preferences' => 1,
					'sub_fields' => array(
						array(
							'key' => 'field_684ace5f2671f',
							'label' => 'Titolo',
							'name' => 'titolo',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_684ace5f23db2',
							'wpml_cf_preferences' => 2,
						),
						array(
							'key' => 'field_684ace5f26759',
							'label' => 'Descrizione',
							'name' => 'descrizione',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_684ace5f23db2',
							'wpml_cf_preferences' => 2,
						),
						array(
							'key' => 'field_684ace5f2684b',
							'label' => 'Immagine',
							'name' => 'immagine',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
							'parent_repeater' => 'field_684ace5f23db2',
							'wpml_cf_preferences' => 1,
						),
						array(
							'key' => 'field_685567281ab5c',
							'label' => 'Link',
							'name' => 'link',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'allow_in_bindings' => 0,
							'parent_repeater' => 'field_684ace5f23db2',
							'wpml_cf_preferences' => 1,
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/slider',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'display_title' => '',
			'allow_ai_access' => false,
			'ai_description' => '',
			'acfml_field_group_mode' => 'translation',
		) );

		acf_add_local_field_group( array(
			'key' => 'group_68665521410aa',
			'title' => 'Block: Splash cover',
			'fields' => array(
				array(
					'key' => 'field_686655a57c8ab',
					'label' => 'Tipo cover',
					'name' => 'tipo_cover',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'immagine' => 'Immagine',
						'video' => 'Video',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_6866552144b47',
					'label' => 'Altezza cover (in pixel)',
					'name' => 'altezza',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 400,
					'min' => '',
					'max' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_686e22d85ae9a',
					'label' => 'Titolo',
					'name' => 'titolo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_686e22e55ae9b',
					'label' => 'Sottotitolo',
					'name' => 'sottotitolo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 2,
				),
				array(
					'key' => 'field_686655ce7c8ac',
					'label' => 'Immagine',
					'name' => 'immagine',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => 'Se il tipo cover è impostato ad "immagine", verrà usato questo campo come sfondo.
						Se invece il tipo cover è impostato a "video", usare questo campo per visualizzare un immagine segnaposto mentre si carica il video.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => 2,
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_686655e17c8ad',
					'label' => 'Video Desktop',
					'name' => 'video_desktop',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => 'Inserire l\'URL di un video ottimizzato per il desktop, per usare file multipli usare il punto e virgola come separatore.
						Formati consigliati: mp4 o webm.
Dimensioni consigliate: 1920x1080 pixel.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_686655a57c8ab',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_686e1cbdfb1d3',
					'label' => 'Video Mobile',
					'name' => 'video_mobile',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => 'Inserire l\'URL di un video ottimizzato per il mobile, per usare file multipli usare il punto e virgola come separatore.
						Formati consigliati: mp4 o webm.
						Dimensioni consigliate: 768x432 pixel.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_686655a57c8ab',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'wpml_cf_preferences' => 1,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/splash-cover',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'display_title' => '',
			'allow_ai_access' => false,
			'ai_description' => '',
			'acfml_field_group_mode' => 'translation',
		) );

		acf_add_local_field_group( array(
			'key' => 'group_6866775f12db5',
			'title' => 'Block: Two images with description',
			'fields' => array(
				array(
					'key' => 'field_6866775fdc4fb',
					'label' => 'Layout',
					'name' => 'layout',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'immagine-grande-destra' => 'Immagine grande a destra',
						'immagine-grande-sinistra' => 'Immagine grande a sinistra',
					),
					'default_value' => 'immagine-grande-destra',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_686677aadc4fc',
					'label' => 'Immagine piccola',
					'name' => 'immagine_piccola',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_686677b3dc4fd',
					'label' => 'Immagine grande',
					'name' => 'immagine_grande',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'wpml_cf_preferences' => 1,
				),
				array(
					'key' => 'field_686677bbdc4fe',
					'label' => 'Descrizione',
					'name' => 'descrizione',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'wpml_cf_preferences' => 2,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'ossigeno/two-images-with-description',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'display_title' => '',
			'allow_ai_access' => false,
			'ai_description' => '',
			'acfml_field_group_mode' => 'translation',
		) );

		// ── ssnail_inquiry CPT fields ────────────────────────────────────────
		acf_add_local_field_group( array(
			'key'      => 'group_ssnail_inquiry',
			'title'    => 'Dati richiesta',
			'fields'   => array(
				array(
					'key'      => 'field_ssnail_inq_nome',
					'name'     => 'ssnail_inq_nome',
					'label'    => 'Nome',
					'type'     => 'text',
					'required' => 1,
				),
				array(
					'key'      => 'field_ssnail_inq_cognome',
					'name'     => 'ssnail_inq_cognome',
					'label'    => 'Cognome',
					'type'     => 'text',
					'required' => 1,
				),
				array(
					'key'      => 'field_ssnail_inq_email',
					'name'     => 'ssnail_inq_email',
					'label'    => 'Email',
					'type'     => 'email',
					'required' => 1,
				),
				array(
					'key'   => 'field_ssnail_inq_oggetto',
					'name'  => 'ssnail_inq_oggetto',
					'label' => 'Oggetto',
					'type'  => 'text',
				),
				array(
					'key'      => 'field_ssnail_inq_messaggio',
					'name'     => 'ssnail_inq_messaggio',
					'label'    => 'Messaggio',
					'type'     => 'textarea',
					'required' => 1,
				),
				array(
					'key'      => 'field_ssnail_inq_privacy',
					'name'     => 'ssnail_inq_privacy',
					'label'    => 'Consenso privacy',
					'type'     => 'true_false',
					'required' => 1,
					'message'  => __( 'Ho letto e accetto la Privacy Policy', 'ossigeno' ),
					'ui'       => 0,
				),
			),
			'location' => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'ssnail_inquiry',
					),
				),
			),
		) );

		// ── ACF Options Page fields (phone, email, offices) ──────────────────
		acf_add_local_field_group( array(
			'key'    => 'group_ssnail_options',
			'title'  => 'Opzioni sito',
			'fields' => array(
				array(
					'key'   => 'field_ssnail_opt_phone',
					'name'  => 'ssnail_opt_phone',
					'label' => 'Telefono',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_ssnail_opt_email',
					'name'  => 'ssnail_opt_email',
					'label' => 'Email',
					'type'  => 'email',
				),
				array(
					'key'          => 'field_ssnail_opt_offices',
					'name'         => 'ssnail_opt_offices',
					'label'        => 'Sedi',
					'type'         => 'repeater',
					'layout'       => 'block',
					'button_label' => __( 'Aggiungi sede', 'ossigeno' ),
					'sub_fields'   => array(
						array(
							'key'   => 'field_ssnail_opt_office_city',
							'name'  => 'city',
							'label' => 'Città',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_ssnail_opt_office_address',
							'name'  => 'address',
							'label' => 'Indirizzo',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_ssnail_opt_office_maps_url',
							'name'  => 'maps_url',
							'label' => 'URL Google Maps (embed)',
							'type'  => 'url',
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options',
					),
				),
			),
		) );

	}
} );
